### ISSUE TITLE
[Usage] shape error raised by apply_rary_pos_emb

### ISSUE THREAD

**Issue by liuruijin17** [zkyredstart/LLaVA-NPU#1]
### Describe the issue

Issue:

Hello, big thx for your great works. I was trying to run on 910B npus and has followed the installation, but I encountered the below erros. Please let me know if you need more information.

Command:
```
bash scripts/v1_5/finetune_npu.sh
```

Log: 
```
q.shape: torch.Size([16, 32, 1417, 128])q.shape: torch.Size([16, 32, 1125, 128])
cos.shape: torch.Size([1, 1, 1125, 1125, 1, 128])
q.shape: torch.Size([1, 1, 1125, 1125, 1, 128])

cos.shape: torch.Size([1, 1, 1417, 1417, 1, 128])
q.shape: torch.Size([1, 1, 1417, 1417, 1, 128])
q.shape: torch.Size([16, 32, 1110, 128])
cos.shape: torch.Size([1, 1, 1110, 1110, 1, 128])
q.shape: torch.Size([1, 1, 1110, 1110, 1, 128])
q.shape: torch.Size([16, 32, 1284, 128])
cos.shape: torch.Size([1, 1, 1284, 1284, 1, 128])
q.shape: torch.Size([1, 1, 1284, 1284, 1, 128])
Traceback (most recent call last):
  File "/home/ma-user/work/LLaVA-NPU/llava/train/train_npu.py", line 14, in <module>
    train()
  File "/home/ma-user/work/LLaVA-NPU/llava/train/train.py", line 976, in train
    trainer.train()
  File "/home/ma-user/anaconda3/envs/llava/lib/python3.9/site-packages/transformers/trainer.py", line 1539, in train
    return inner_training_loop(
  File "/home/ma-user/anaconda3/envs/llava/lib/python3.9/site-packages/transformers/trainer.py", line 1869, in _inner_training_loop
    tr_loss_step = self.training_step(model, inputs)
  File "/home/ma-user/anaconda3/envs/llava/lib/python3.9/site-packages/transformers/trainer.py", line 2772, in training_step
    loss = self.compute_loss(model, inputs)
  File "/home/ma-user/anaconda3/envs/llava/lib/python3.9/site-packages/transformers/trainer.py", line 2795, in compute_loss
    outputs = model(**inputs)
  File "/home/ma-user/anaconda3/envs/llava/lib/python3.9/site-packages/torch/nn/modules/module.py", line 1518, in _wrapped_call_impl
    return self._call_impl(*args, **kwargs)
  File "/home/ma-user/anaconda3/envs/llava/lib/python3.9/site-packages/torch/nn/modules/module.py", line 1527, in _call_impl
    return forward_call(*args, **kwargs)
  File "/home/ma-user/anaconda3/envs/llava/lib/python3.9/site-packages/deepspeed/utils/nvtx.py", line 15, in wrapped_fn
    ret_val = func(*args, **kwargs)
  File "/home/ma-user/anaconda3/envs/llava/lib/python3.9/site-packages/deepspeed/runtime/engine.py", line 1833, in forward
    loss = self.module(*inputs, **kwargs)
  File "/home/ma-user/anaconda3/envs/llava/lib/python3.9/site-packages/torch/nn/modules/module.py", line 1518, in _wrapped_call_impl
    return self._call_impl(*args, **kwargs)
  File "/home/ma-user/anaconda3/envs/llava/lib/python3.9/site-packages/torch/nn/modules/module.py", line 1568, in _call_impl
    result = forward_call(*args, **kwargs)
  File "/home/ma-user/work/LLaVA-NPU/llava/model/language_model/llava_llama.py", line 91, in forward
    return super().forward(
  File "/home/ma-user/anaconda3/envs/llava/lib/python3.9/site-packages/transformers/models/llama/modeling_llama.py", line 1186, in forward
    outputs = self.model(
  File "/home/ma-user/anaconda3/envs/llava/lib/python3.9/site-packages/torch/nn/modules/module.py", line 1518, in _wrapped_call_impl
    return self._call_impl(*args, **kwargs)
  File "/home/ma-user/anaconda3/envs/llava/lib/python3.9/site-packages/torch/nn/modules/module.py", line 1568, in _call_impl
    result = forward_call(*args, **kwargs)
  File "/home/ma-user/anaconda3/envs/llava/lib/python3.9/site-packages/transformers/models/llama/modeling_llama.py", line 1063, in forward
    layer_outputs = self._gradient_checkpointing_func(
  File "/home/ma-user/anaconda3/envs/llava/lib/python3.9/site-packages/torch/_compile.py", line 24, in inner
    return torch._dynamo.disable(fn, recursive)(*args, **kwargs)
  File "/home/ma-user/anaconda3/envs/llava/lib/python3.9/site-packages/torch/_dynamo/eval_frame.py", line 328, in _fn
    return fn(*args, **kwargs)
  File "/home/ma-user/anaconda3/envs/llava/lib/python3.9/site-packages/torch/_dynamo/external_utils.py", line 17, in inner
    return fn(*args, **kwargs)
  File "/home/ma-user/anaconda3/envs/llava/lib/python3.9/site-packages/torch/utils/checkpoint.py", line 451, in checkpoint
    return CheckpointFunction.apply(function, preserve, *args)
  File "/home/ma-user/anaconda3/envs/llava/lib/python3.9/site-packages/torch/autograd/function.py", line 539, in apply
    return super().apply(*args, **kwargs)  # type: ignore[misc]
  File "/home/ma-user/anaconda3/envs/llava/lib/python3.9/site-packages/torch/utils/checkpoint.py", line 230, in forward
    outputs = run_function(*args)
  File "/home/ma-user/anaconda3/envs/llava/lib/python3.9/site-packages/torch/nn/modules/module.py", line 1518, in _wrapped_call_impl
    return self._call_impl(*args, **kwargs)
  File "/home/ma-user/anaconda3/envs/llava/lib/python3.9/site-packages/torch/nn/modules/module.py", line 1568, in _call_impl
    result = forward_call(*args, **kwargs)
  File "/home/ma-user/anaconda3/envs/llava/lib/python3.9/site-packages/transformers/models/llama/modeling_llama.py", line 801, in forward
    hidden_states, self_attn_weights, present_key_value = self.self_attn(
  File "/home/ma-user/anaconda3/envs/llava/lib/python3.9/site-packages/torch/nn/modules/module.py", line 1518, in _wrapped_call_impl
    return self._call_impl(*args, **kwargs)
  File "/home/ma-user/anaconda3/envs/llava/lib/python3.9/site-packages/torch/nn/modules/module.py", line 1568, in _call_impl
    result = forward_call(*args, **kwargs)
  File "/home/ma-user/anaconda3/envs/llava/lib/python3.9/site-packages/transformers/models/llama/modeling_llama.py", line 709, in forward
    query_states, key_states = apply_rotary_pos_emb(query_states, key_states, cos, sin, position_ids)
  File "/home/ma-user/anaconda3/envs/llava/lib/python3.9/site-packages/transformers/models/llama/modeling_llama.py", line 237, in apply_rotary_pos_emb
    q_embed = (q * cos) + (rotate_half(q) * sin)
RuntimeError: The size of tensor a (32) must match the size of tensor b (1417) at non-singleton dimension 3

RuntimeError: The size of tensor a (32) must match the size of tensor b (1284) at non-singleton dimension 3

RuntimeError: The size of tensor a (32) must match the size of tensor b (1110) at non-singleton dimension 3
```

**Comment by zkyntu** [comment]
@liuruijin17 Hi, this is my second account. I suggest that you first run the pertaining and then run the fintune. I find directly using the pretraining weight of the official repo is wrong for Ascend devices.

**Comment by liuruijin17** [comment]
@zkyntu Hi. Still the same shape mismatch problem during pretraining. I run the pretraining scipt by:
```
source /home/ma-user/Ascend/ascend-toolkit/set_env.sh

deepspeed llava/train/train_mem_npu.py \
    --deepspeed ./scripts/zero2.json \
    --model_name_or_path lmsys/vicuna-7b-v1.5 \
    --version plain \
    --data_path ./playground/data/LLaVA-Pretrain/blip_laion_cc_sbu_558k.json \
    --image_folder ./playground/data/LLaVA-Pretrain/images \
    --vision_tower openai/clip-vit-large-patch14-336 \
    --mm_projector_type mlp2x_gelu \
    --tune_mm_mlp_adapter True \
    --mm_vision_select_layer -2 \
    --mm_use_im_start_end False \
    --mm_use_im_patch_token False \
    --bf16 True \
    --output_dir ./checkpoints/llava-v1.5-7b-pretrain \
    --num_train_epochs 1 \
    --per_device_train_batch_size 8 \
    --per_device_eval_batch_size 4 \
    --gradient_accumulation_steps 4 \
    --evaluation_strategy "no" \
    --save_strategy "steps" \
    --save_steps 24000 \
    --save_total_limit 1 \
    --learning_rate 1e-3 \
    --weight_decay 0. \
    --warmup_ratio 0.03 \
    --lr_scheduler_type "cosine" \
    --logging_steps 1 \
    --tf32 False \
    --model_max_length 2048 \
    --gradient_checkpointing True \
    --dataloader_num_workers 4 \
    --lazy_preprocess True \
    --report_to wandb
```

and the train_mem_npu.py follow your train_npu.py:

```
from llava.train.llama_npu_monkey_patch import (
    replace_with_torch_npu_flash_attention,
    replace_with_torch_npu_rmsnorm
)

replace_with_torch_npu_flash_attention()
replace_with_torch_npu_rmsnorm()

from llava.train.train import train
import torch_npu
from torch_npu.contrib import transfer_to_npu

if __name__ == "__main__":
    train()
```

Also, I did not download openai/clip-vit-large-patch14-336 and lmsys/vicuna-7b-v1.5, but I notice that the code is loading some checkpoint shards, which makes me very confused
```
Loading checkpoint shards:   0%|                                                                                                         | 0/2 [00:00<?, ?it/s]/home/ma-user/anaconda3/envs/llava/lib/python3.9/site-packages/torch/_utils.py:831: UserWarning: TypedStorage is deprecated. It will be removed in the future and UntypedStorage will be the only storage class. This should only matter to you if you are using storages directly.  To access UntypedStorage directly, use tensor.untyped_storage() instead of tensor.storage()
  return self.fget.__get__(instance, owner)()
Loading checkpoint shards:   0%|                                                                                                         | 0/2 [00:00<?, ?it/s]/home/ma-user/anaconda3/envs/llava/lib/python3.9/site-packages/torch/_utils.py:831: UserWarning: TypedStorage is deprecated. It will be removed in the future and UntypedStorage will be the only storage class. This should only matter to you if you are using storages directly.  To access UntypedStorage directly, use tensor.untyped_storage() instead of tensor.storage()
  return self.fget.__get__(instance, owner)()
Loading checkpoint shards:   0%|                                                                                                         | 0/2 [00:00<?, ?it/s]/home/ma-user/anaconda3/envs/llava/lib/python3.9/site-packages/torch/_utils.py:831: UserWarning: TypedStorage is deprecated. It will be removed in the future and UntypedStorage will be the only storage class. This should only matter to you if you are using storages directly.  To access UntypedStorage directly, use tensor.untyped_storage() instead of tensor.storage()
  return self.fget.__get__(instance, owner)()
Loading checkpoint shards:   0%|                                                                                                         | 0/2 [00:00<?, ?it/s]/home/ma-user/anaconda3/envs/llava/lib/python3.9/site-packages/torch/_utils.py:831: UserWarning: TypedStorage is deprecated. It will be removed in the future and UntypedStorage will be the only storage class. This should only matter to you if you are using storages directly.  To access UntypedStorage directly, use tensor.untyped_storage() instead of tensor.storage()
  return self.fget.__get__(instance, owner)()
Loading checkpoint shards:   0%|                                                                                                         | 0/2 [00:00<?, ?it/s]/home/ma-user/anaconda3/envs/llava/lib/python3.9/site-packages/torch/_utils.py:831: UserWarning: TypedStorage is deprecated. It will be removed in the future and UntypedStorage will be the only storage class. This should only matter to you if you are using storages directly.  To access UntypedStorage directly, use tensor.untyped_storage() instead of tensor.storage()
  return self.fget.__get__(instance, owner)()
Loading checkpoint shards:   0%|                                                                                                         | 0/2 [00:00<?, ?it/s]/home/ma-user/anaconda3/envs/llava/lib/python3.9/site-packages/torch/_utils.py:831: UserWarning: TypedStorage is deprecated. It will be removed in the future and UntypedStorage will be the only storage class. This should only matter to you if you are using storages directly.  To access UntypedStorage directly, use tensor.untyped_storage() instead of tensor.storage()
  return self.fget.__get__(instance, owner)()
Loading checkpoint shards:   0%|                                                                                                         | 0/2 [00:00<?, ?it/s]/home/ma-user/anaconda3/envs/llava/lib/python3.9/site-packages/torch/_utils.py:831: UserWarning: TypedStorage is deprecated. It will be removed in the future and UntypedStorage will be the only storage class. This should only matter to you if you are using storages directly.  To access UntypedStorage directly, use tensor.untyped_storage() instead of tensor.storage()
  return self.fget.__get__(instance, owner)()
Loading checkpoint shards:   0%|                                                                                                         | 0/2 [00:00<?, ?it/s]/home/ma-user/anaconda3/envs/llava/lib/python3.9/site-packages/torch/_utils.py:831: UserWarning: TypedStorage is deprecated. It will be removed in the future and UntypedStorage will be the only storage class. This should only matter to you if you are using storages directly.  To access UntypedStorage directly, use tensor.untyped_storage() instead of tensor.storage()
  return self.fget.__get__(instance, owner)()
Loading checkpoint shards: 100%|█████████████████████████████████████████████████████████████████████████████████████████████████| 2/2 [00:13<00:00,  6.93s/it]
/home/ma-user/anaconda3/envs/llava/lib/python3.9/site-packages/transformers/generation/configuration_utils.py:392: UserWarning: `do_sample` is set to `False`. However, `temperature` is set to `0.9` -- this flag is only used in sample-based generation modes. You should set `do_sample=True` or unset `temperature`. This was detected when initializing the generation config instance, which means the corresponding file may hold incorrect parameterization and should be fixed.
  warnings.warn(
/home/ma-user/anaconda3/envs/llava/lib/python3.9/site-packages/transformers/generation/configuration_utils.py:397: UserWarning: `do_sample` is set to `False`. However, `top_p` is set to `0.6` -- this flag is only used in sample-based generation modes. You should set `do_sample=True` or unset `top_p`. This was detected when initializing the generation config instance, which means the corresponding file may hold incorrect parameterization and should be fixed.
  warnings.warn(
model_args.model_name_or_path: lmsys/vicuna-7b-v1.5
Loading checkpoint shards: 100%|█████████████████████████████████████████████████████████████████████████████████████████████████| 2/2 [00:16<00:00,  8.43s/it]
Loading checkpoint shards: 100%|█████████████████████████████████████████████████████████████████████████████████████████████████| 2/2 [00:16<00:00,  8.37s/it]
Loading checkpoint shards: 100%|█████████████████████████████████████████████████████████████████████████████████████████████████| 2/2 [00:15<00:00,  7.63s/it]
Loading checkpoint shards: 100%|█████████████████████████████████████████████████████████████████████████████████████████████████| 2/2 [00:15<00:00,  7.57s/it]
model_args.vision_tower: openai/clip-vit-large-patch14-336
Loading checkpoint shards: 100%|█████████████████████████████████████████████████████████████████████████████████████████████████| 2/2 [00:16<00:00,  8.33s/it]
Loading checkpoint shards: 100%|█████████████████████████████████████████████████████████████████████████████████████████████████| 2/2 [00:16<00:00,  8.02s/it]

```

**Comment by zkyntu** [comment]
@liuruijin17 Hi, the code will download the weight of CLIP and Vicuna, but I suggest that you can download the weight manually.

**Comment by zkyntu** [comment]
I have a way to test the code: 1) download the official LLaVa1.5 weight and then run the evaluation or inference. I find this problem is the model architecture. If you have any questions, feel free to ask.

**Comment by liuruijin17** [comment]
@zkyntu Hi, I find the shape mismatch is caused by `class FlashLlamaRotaryEmbedding(LlamaRotaryEmbedding)` in llama_npu_monkey_patch.py and change `def _set_cos_sin_cache(self, seq_len, device, dtype):` and `def forward(self, x, seq_len=None):` follows transformers/models/llama/modelling_llama.py

The result is:
```
class FlashLlamaRotaryEmbedding(LlamaRotaryEmbedding):
    """LlamaRotaryEmbedding extended with linear scaling. Credits to the Reddit user /u/kaiokendev"""

    def _set_cos_sin_cache(self, seq_len, device, dtype):
        self.max_seq_len_cached = seq_len
        t = torch.arange(self.max_seq_len_cached, device=device, dtype=self.inv_freq.dtype)

        freqs = torch.einsum("i,j->ij", t, self.inv_freq)

        # Different from paper, but it uses a different permutation in order to obtain the same calculation
        emb = torch.cat((freqs, freqs), dim=-1)
        #self.register_buffer("cos_cached", emb.cos()[None, :, None, :].to(dtype), persistent=False)
        #self.register_buffer("sin_cached", emb.sin()[None, :, None, :].to(dtype), persistent=False)
        self.register_buffer("cos_cached", emb.cos().to(dtype), persistent=False)
        self.register_buffer("sin_cached", emb.sin().to(dtype), persistent=False)

    def forward(self, x, seq_len=None):
        # x: [bs, num_attention_heads, seq_len, head_size]
        if seq_len > self.max_seq_len_cached:
            self._set_cos_sin_cache(seq_len=seq_len, device=x.device, dtype=x.dtype)
        # return (
        #     self.cos_cached[:, :seq_len, :, ...].to(dtype=x.dtype),
        #     self.sin_cached[:, :seq_len, :, ...].to(dtype=x.dtype),
        # )
        return (
            self.cos_cached[:seq_len, ...].to(dtype=x.dtype),
            self.sin_cached[:seq_len, ...].to(dtype=x.dtype),
        )
```


However, the finetune_npu.sh still cannot run, and I encounter an error which is an HCCL commucation error. Do you have any idea about it?

```
EI0006: [PID: 1997610] 2024-09-25-10:50:49.716.602 Getting socket times out. Reason: 1. The remote does not initiate a connect request. some NPUs in the cluster are abnormal.    2. The remote does not initiate a connect request because the collective communication operator is started too late or is not started by some NPU in the cluster.    3. The communication link is disconnected. (For example, the IP addresses are not on the same network segment or the TLS configurations are inconsistent.)
        Solution: 1. Check the rank service processes with other errors or no errors in the cluster.2. If this error is reported for all NPUs, check whether the time difference between the earliest and latest errors is greater than the connect timeout interval (120s by default). If so, adjust the timeout interval by using the HCCL_CONNECT_TIMEOUT environment variable.3. Check the connectivity of the communication link between nodes. (For details, see the TLS command and HCCN connectivity check examples.). For details:https://www.hiascend.com/document

Traceback (most recent call last):
  File "/home/ma-user/work/LLaVA-NPU/llava/train/train_npu.py", line 17, in <module>
    train()
  File "/home/ma-user/work/LLaVA-NPU/./llava/train/train.py", line 986, in train
    trainer.train()
  File "/home/ma-user/anaconda3/envs/llava/lib/python3.9/site-packages/transformers/trainer.py", line 1539, in train
    return inner_training_loop(
  File "/home/ma-user/anaconda3/envs/llava/lib/python3.9/site-packages/transformers/trainer.py", line 1869, in _inner_training_loop
    tr_loss_step = self.training_step(model, inputs)
  File "/home/ma-user/anaconda3/envs/llava/lib/python3.9/site-packages/transformers/trainer.py", line 2781, in training_step
    self.accelerator.backward(loss)
  File "/home/ma-user/anaconda3/envs/llava/lib/python3.9/site-packages/accelerate/accelerator.py", line 1847, in backward
    self.deepspeed_engine_wrapped.backward(loss, **kwargs)
  File "/home/ma-user/anaconda3/envs/llava/lib/python3.9/site-packages/accelerate/utils/deepspeed.py", line 167, in backward
    self.engine.backward(loss, **kwargs)
  File "/home/ma-user/anaconda3/envs/llava/lib/python3.9/site-packages/deepspeed/utils/nvtx.py", line 15, in wrapped_fn
    ret_val = func(*args, **kwargs)
  File "/home/ma-user/anaconda3/envs/llava/lib/python3.9/site-packages/deepspeed/runtime/engine.py", line 1955, in backward
    self.optimizer.backward(loss, retain_graph=retain_graph)
  File "/home/ma-user/anaconda3/envs/llava/lib/python3.9/site-packages/deepspeed/utils/nvtx.py", line 15, in wrapped_fn
    ret_val = func(*args, **kwargs)
  File "/home/ma-user/anaconda3/envs/llava/lib/python3.9/site-packages/deepspeed/runtime/zero/stage3.py", line 2135, in backward
    self.loss_scaler.backward(loss.float(), retain_graph=retain_graph)
  File "/home/ma-user/anaconda3/envs/llava/lib/python3.9/site-packages/deepspeed/runtime/fp16/loss_scaler.py", line 63, in backward
    scaled_loss.backward(retain_graph=retain_graph)
  File "/home/ma-user/anaconda3/envs/llava/lib/python3.9/site-packages/torch/_tensor.py", line 492, in backward
    torch.autograd.backward(
  File "/home/ma-user/anaconda3/envs/llava/lib/python3.9/site-packages/torch/autograd/__init__.py", line 251, in backward
    Variable._execution_engine.run_backward(  # Calls into the C++ engine to run the backward pass
  File "/home/ma-user/anaconda3/envs/llava/lib/python3.9/site-packages/torch/autograd/function.py", line 288, in apply
    return user_fn(self, *args)
  File "/home/ma-user/anaconda3/envs/llava/lib/python3.9/site-packages/torch/utils/checkpoint.py", line 271, in backward
    outputs = ctx.run_function(*detached_inputs)
  File "/home/ma-user/anaconda3/envs/llava/lib/python3.9/site-packages/torch/nn/modules/module.py", line 1518, in _wrapped_call_impl
    return self._call_impl(*args, **kwargs)
  File "/home/ma-user/anaconda3/envs/llava/lib/python3.9/site-packages/torch/nn/modules/module.py", line 1568, in _call_impl
    result = forward_call(*args, **kwargs)
  File "/home/ma-user/anaconda3/envs/llava/lib/python3.9/site-packages/transformers/models/llama/modeling_llama.py", line 798, in forward
    hidden_states, self_attn_weights, present_key_value = self.self_attn(
  File "/home/ma-user/anaconda3/envs/llava/lib/python3.9/site-packages/torch/nn/modules/module.py", line 1518, in _wrapped_call_impl
    return self._call_impl(*args, **kwargs)
  File "/home/ma-user/anaconda3/envs/llava/lib/python3.9/site-packages/torch/nn/modules/module.py", line 1568, in _call_impl
    result = forward_call(*args, **kwargs)
  File "/home/ma-user/anaconda3/envs/llava/lib/python3.9/site-packages/transformers/models/llama/modeling_llama.py", line 694, in forward
    key_states = self.k_proj(hidden_states)
  File "/home/ma-user/anaconda3/envs/llava/lib/python3.9/site-packages/torch/nn/modules/module.py", line 1518, in _wrapped_call_impl
    return self._call_impl(*args, **kwargs)
  File "/home/ma-user/anaconda3/envs/llava/lib/python3.9/site-packages/torch/nn/modules/module.py", line 1557, in _call_impl
    args_result = hook(self, args)
  File "/home/ma-user/anaconda3/envs/llava/lib/python3.9/site-packages/deepspeed/utils/nvtx.py", line 15, in wrapped_fn
    ret_val = func(*args, **kwargs)
  File "/home/ma-user/anaconda3/envs/llava/lib/python3.9/site-packages/deepspeed/runtime/zero/parameter_offload.py", line 392, in _pre_forward_module_hook
    self.pre_sub_module_forward_function(module)
  File "/home/ma-user/anaconda3/envs/llava/lib/python3.9/site-packages/deepspeed/runtime/zero/parameter_offload.py", line 505, in pre_sub_module_forward_function
    param_coordinator.fetch_sub_module(sub_module, forward=prev_grad_state)
  File "/home/ma-user/anaconda3/envs/llava/lib/python3.9/site-packages/deepspeed/utils/nvtx.py", line 15, in wrapped_fn
    ret_val = func(*args, **kwargs)
  File "/home/ma-user/anaconda3/envs/llava/lib/python3.9/site-packages/torch/utils/_contextlib.py", line 115, in decorate_context
    return func(*args, **kwargs)
  File "/home/ma-user/anaconda3/envs/llava/lib/python3.9/site-packages/deepspeed/runtime/zero/partitioned_param_coordinator.py", line 301, in fetch_sub_module
    self.__ongoing_fetch_events.popleft().synchronize()
  File "/home/ma-user/anaconda3/envs/llava/lib/python3.9/site-packages/torch_npu/npu/streams.py", line 179, in synchronize
    super(Event, self).synchronize()
RuntimeError: The Inner error is reported as above.
 Since the operator is called asynchronously, the stacktrace may be inaccurate. If you want to get the accurate stacktrace, pleace set the environment variable ASCEND_LAUNCH_BLOCKING=1.
[ERROR] 2024-09-25-10:50:49 (PID:1997610, Device:0, RankID:0) ERR00100 PTA call acl api failed

```

**Comment by zkyntu** [comment]
@liuruijin17  Hi, what is the version of your transformers? It should be noted that transformers==4.37.2.

**Comment by zkyntu** [comment]
I suggest that you can check the version of the dependency.

**Comment by liuruijin17** [comment]
@zkyntu Hi, the transformers==4.37.2, I follow your install script. Now, I use zero3_offload.json, and the training run perfectly. Thanks a lot!

**Comment by pickxiguapi** [comment]
Hi, I had the same problem as you, I checked the transformer version is 4.37.2, may I ask how you finally solved it?


```
Bash:

deepspeed  llava/train/train_npu.py \
    --deepspeed ./scripts/zero2.json \
    --model_name_or_path lmsys/vicuna-7b-v1.5 \
    --version v1 \
    --data_path /mnt/blip_laion_cc_sbu_558k.json \
    --image_folder /mnt/llava_pretrain_datasets/ \
    --vision_tower openai/clip-vit-large-patch14-336 \
    --mm_projector_type mlp2x_gelu \
    --mm_vision_select_layer -2 \
    --mm_use_im_start_end False \
    --mm_use_im_patch_token False \
    --bf16 True \
    --output_dir ./checkpoints/llava-v1.5-7b \
    --num_train_epochs 1 \
    --per_device_train_batch_size 32 \
    --per_device_eval_batch_size 4 \
    --gradient_accumulation_steps 1 \
    --evaluation_strategy "no" \
    --save_strategy "steps" \
    --save_steps 50000 \
    --save_total_limit 1 \
    --learning_rate 2e-5 \
    --weight_decay 0. \
    --warmup_ratio 0.03 \
    --lr_scheduler_type "cosine" \
    --logging_steps 1 \
    --tf32 False \
    --model_max_length 2048 \
    --gradient_checkpointing True \
    --dataloader_num_workers 4 \
    --lazy_preprocess True \
    --report_to wandb```

Error:


  File "/usr/local/python3.10/lib/python3.10/site-packages/transformers/models/llama/modeling_llama.py", line 234, in apply_rotary_pos_emb
    q_embed = (q * cos) + (rotate_half(q) * sin)
RuntimeError: The size of tensor a (32) must match the size of tensor b (658) at non-singleton dimension 3


```

**Comment by zkyntu** [comment]
Hi, could you run the inference code using the official weight? This is a way to test the code.

**Comment by zkyntu** [comment]
Besides, the official Ascend repo has released the LLaVA1.5 code. I suggest that you use their code. The link is [here](https://gitee.com/ascend/MindSpeed-MM).
